import Head from "next/head";
import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import { Navbar } from "~/components/Navbar";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Ai Streamer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-gradient-to-b from-[#2e026d] to-[#15162c] py-8 px-4">
        <Navbar
          status={status}
          user={session?.user}
          title="Ai Streamer platform"
        />
        <div className="container flex flex-col items-center justify-center gap-12"></div>
      </main>
    </>
  );
};

export default Home;
